"""update knowledge documents schema

Revision ID: 238763153683
Revises: ca889a41a376
Create Date: 2026-09-04 21:09:51.565061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238763153683'
down_revision: Union[str, Sequence[str], None] = 'ca889a41a376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.add_column('knowledge_documents', sa.Column('scope_type', sa.String(length=50), nullable=False))
    op.add_column('knowledge_documents', sa.Column('scope_value', sa.String(length=255), nullable=True))
    op.add_column('knowledge_documents', sa.Column('section', sa.String(length=100), nullable=False))
    op.add_column('knowledge_documents', sa.Column('subsection', sa.String(length=255), nullable=True))
    op.add_column('knowledge_documents', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.drop_column('knowledge_documents', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('knowledge_documents', 'chunk_index')
    op.drop_column('knowledge_documents', 'subsection')
    op.drop_column('knowledge_documents', 'section')
    op.drop_column('knowledge_documents', 'scope_value')
    op.drop_column('knowledge_documents', 'scope_type')
    op.drop_column('knowledge_documents', 'document_type')
    # ### end Alembic commands ###
